---
- name: "s'assurer qu'Apache est desinstallé sur RedHat Debian/Ubuntu"
  hosts: 
    - all
    - centos
  gather_facts: yes
  tasks:
  - name: "s'assurer que le paquet apache est présent (RedHat)"
    yum:
      name: httpd
      autoremove: yes
      state: absent
    when: ansible_os_family == 'RedHat'
  - name: "s'assurer que le paquet apache est présent (Debian/Ubuntu)"
    apt:
      name: apache2
      autoremove: yes
      state: absent
    when: ansible_os_family == 'Debian'
  - name: "s'assurer de la présence d'une page d'accueil personalisé"
    file:
      path: /var/www/html/index.html
      state: absent
  - name: "s'assurer que le parefeu est configuré pour apache"
    firewalld:
      permanent: yes
      immediate: yes
      service: http
      state: disabled
    when: ansible_os_family == 'RedHat'
...
