- name: "Mise en oeuvre Grafana"
  hosts:
    - centosnfs
  gather_facts: no
  tasks:
  - name: "Add grafana"
    yum:
      name: grafana
  - name: "Grafana is started"
    systemd:
      name: grafana
      state: started
      enabled: yes
  - name: "firewall is open on 3000"
    firewalld:
      port: 3000/tcp
      permanent: yes
      immediate: yes
      enabled: yes


