apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploiement-avec-placement
spec:
 replicas: 15
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
    containers:
    - name: web
      image: nginx:alpine
    nodeSelector:
      carte_encodeur: Z81245